--NOMBRE DE LAS BASES DE DATOS EN POSTGRESQL Y SQL SERVER: BDPRODUCTO
--EN ORACLE se accede a la instancia con el nombre de usuario



--************************************ORACLE*********************
--TABLA DE ORACLE
create table PRODUCTO 
(
   ID_PRODUCTO          VARCHAR2(10),
   DESCRIPCION          VARCHAR2(20),
   PRECIO        	NUMBER(7,2),
   FECHA          DATE
);

--PROCEDIMIENTO ALMACENADO CON ORACLE - PLSQL

create or replace PROCEDURE PA_INSERTARPRODUCTO(PIDPRODUCTO IN PRODUCTO.ID_PRODUCTO%TYPE, PDESCRIPCION IN PRODUCTO.DESCRIPCION%TYPE,
PPRECIO IN PRODUCTO.PRECIO%TYPE, PFECHA IN PRODUCTO.FECHA%TYPE)
AS
BEGIN 
INSERT INTO PRODUCTO VALUES (PIDPRODUCTO, PDESCRIPCION, PPRECIO, PFECHA);
END PA_INSERTARPRODUCTO;



--************************************POSTGRESQL*********************
--TABLA DE POSTGRESQL
create table PRODUCTO 
(
   ID_PRODUCTO           VARCHAR(10),
   DESCRIPCION          VARCHAR(20),
   PRECIO        	NUMERIC(7,2),
   FECHA         DATE
);

--PROCEDIMIENTO ALMACENADO EN POSTGRESQL (EL %TYPE NO SE USA CON  LOS TIPOS DECIMALES, SE USA DIRECTAMENTE FLOAT PARA QUE EL PROCEDIMIENTO ALMACENADO TOME LOS PARAMETROS
-- COMO "DOUBLE PRECCISSION", CASO CONTRARIO LOS TOMARIA COMO "NUMERIC" Y NO SE RECONOCE EN LAS LLAMADAS DESDE JAVA    - PL/PGSQL

create or replace function PA_INSERTARPRODUCTO(PIDPRODUCTO PRODUCTO.ID_PRODUCTO%TYPE,
PDESCRIPCION PRODUCTO.DESCRIPCION%TYPE, PPRECIO FLOAT, PFECHA DATE) returns void as $$
Begin
   INSERT INTO PRODUCTO VALUES (PIDPRODUCTO, PDESCRIPCION, PPRECIO, PFECHA);
end;
$$ LANGUAGE plpgsql;



--************************************SQLSERVER*********************
--TABLA DE SQLSERVER
create table PRODUCTO 
(
   ID_PRODUCTO           VARCHAR(10),
   DESCRIPCION          VARCHAR(20),
   PRECIO        	NUMERIC(7,2),
   FECHA         DATE
);

--PROCEDIMIENTO ALMACENADO EN SQLSERVER  - TSQL

CREATE PROCEDURE PA_INSERTARPRODUCTO (@PIDPRODUCTO VARCHAR(10), @PDESCRIPCION VARCHAR(50), @PPRECIO NUMERIC(7,2), @PFECHA DATE)
AS
BEGIN
INSERT INTO PRODUCTO VALUES  (@PIDPRODUCTO, @PDESCRIPCION , @PPRECIO, @PFECHA)
END



--**********************************MYSQL*********************
--TABLA DE MYSQL
create table PRODUCTO 
(
   ID_PRODUCTO           VARCHAR(10),
   DESCRIPCION          VARCHAR(20),
   PRECIO        	NUMERIC(7,2),
   FECHA          DATE
);

--PROCEDIMIENTO ALMACENADO EN MYSQL

create PROCEDURE PA_INSERTARPRODUCTO(IN PIDPRODUCTO varchar(10), IN PDESCRIPCION varchar(50), IN PPRECIO NUMERIC, IN PFECHA DATE)
BEGIN
INSERT INTO PRODUCTO(id_producto,descripcion,precio,fecha) VALUES (PIDPRODUCTO,PDESCRIPCION,PPRECIO,PFECHA);
END;
